version: '2'
services:
  nginx:
    image: 'nginx'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /Users/lepetitdev/Dev/DevOpsCount/var/www:/var/www
    networks:
      - back
    links:
      - mysql
  mysql:
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - back
    volumes:
      - /Users/lepetitdev/Dev/DevOpsCount/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - back
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
networks:
  back: